import streamlit as st
import pandas as pd

st.set_page_config(page_title="TED Tender Intelligence", layout="wide")

st.title("TED Tender Intelligence — DevelopMinded")

uploaded = st.file_uploader("Upload ted_tenders.xlsx", type=["xlsx"])

if uploaded:
    live = pd.read_excel(uploaded, sheet_name="Live Opportunities")
    st.subheader("Live Opportunities")
    st.dataframe(live, use_container_width=True)

    try:
        intel = pd.read_excel(uploaded, sheet_name="Market Intelligence")
        st.subheader("Market Intelligence")
        st.dataframe(intel, use_container_width=True)
    except Exception:
        pass
else:
    st.info("Upload the Excel file generated by GitHub Actions.")
